(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], C=window.CONSOLE, D=C.DATA, O=C.ORDER;
const meta=new URLSearchParams(location.search).has('meta')||location.hash==='#meta'; C.meta=meta; if(meta)document.body.classList.add('meta');
let z=40,prev=null,dynamicCounter=0,dragDepth=0;
const prof=()=>innerWidth<=720?'mobile':'desktop', key=()=>`observer-console-v09-${prof()}`;
function defaults(id){const m=prof()==='mobile',map=m?{workspace:[14,28,250,'square'],alerts:[innerWidth-108,28,88,'node'],overview:[innerWidth-108,130,88,'node'],resume:[14,298,228,'round'],systems:[innerWidth-108,232,88,'node'],projects:[innerWidth-108,334,88,'node'],inbox:[18,520,86,'node'],calendar:[112,520,86,'node'],assistant:[206,520,86,'node']}:{workspace:[50,46,360,'square'],alerts:[innerWidth-340,48,275,'round'],resume:[44,424,300,'round'],overview:[innerWidth*.5-142,58,284,'round'],systems:[innerWidth-355,414,302,'square'],projects:[innerWidth*.5-160,432,320,'square'],inbox:[innerWidth-225,275,94,'node'],calendar:[72,285,94,'node'],assistant:[innerWidth*.5-47,316,94,'node']};return map[id]||[60+dynamicCounter*28%Math.max(80,innerWidth-420),70+dynamicCounter*22%Math.max(80,innerHeight-420),340,'square']}
function escapeHTML(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function objectHTML(d){return `<div class="shell"><div class="stage"><div class="head"><span class="marker"></span><span class="name">${escapeHTML(d.name)}</span><span class="kind">${escapeHTML(d.kind||'OBJECT')}</span><span class="state">${escapeHTML(d.state||'READY')}</span></div><div class="contentViewport"><div class="contentFit">${d.html||''}</div></div><div class="tools"><button class="tool shape" title="square / round">○</button><button class="tool node" title="collapse to node">•</button><button class="tool pin" title="pin">⌖</button><button class="tool duplicate" title="duplicate">⧉</button><button class="tool focus" title="focus">↗</button><button class="tool dismiss" title="dismiss">×</button></div><div class="pinMark">PIN</div></div></div><div class="resize"></div><div class="nodeLabel"><b>${escapeHTML(d.name)}</b><span>${escapeHTML(d.state||'READY')}</span></div>`}
function make(id,d=D[id],dynamic=false){const f=document.createElement('article');f.className='frame'+(d.hot?' alert attention':'');f.dataset.id=id;f.dataset.dynamic=dynamic?'1':'0';f.style.setProperty('--accent',d.hot?'#ff1830':'#fff');f.innerHTML=objectHTML(d);$('#workspace').append(f);wire(f);apply(f,dynamic);bindObjectActions(f);return f}
O.forEach(id=>make(id));
function fit(f){if(f.classList.contains('node'))return;const i=f.querySelector('.contentViewport'),c=f.querySelector('.contentFit');if(!i||!c)return;c.style.transform='none';c.style.width='100%';c.style.height='100%';if(c.querySelector('.viewer,.chatSurface,.terminal,.noteArea'))return;const s=Math.min(1,i.clientWidth/Math.max(c.scrollWidth,1),i.clientHeight/Math.max(c.scrollHeight,1));c.style.transform=`scale(${s})`}
function scale(f){if(f.classList.contains('node'))return;const w=parseFloat(f.style.width)||f.offsetWidth,k=w/360,s=f.querySelector('.stage');if(!s)return;s.style.zoom='';s.style.transform='none';if('zoom'in s.style)s.style.zoom=k;else{s.style.transform=`scale(${k})`;s.style.transformOrigin='top left'};requestAnimationFrame(()=>fit(f))}
$$('.frame').forEach(f=>new ResizeObserver(()=>scale(f)).observe(f));
function apply(f,dynamic=false){const v=defaults(f.dataset.id);if(dynamic)dynamicCounter++;f.style.left=Math.max(6,v[0])+'px';f.style.top=Math.max(6,v[1])+'px';f.style.width=f.style.height=v[2]+'px';f.classList.toggle('round',v[3]==='round');f.classList.toggle('node',v[3]==='node');scale(f)}
function stateOf(f){return {l:parseFloat(f.style.left)||0,t:parseFloat(f.style.top)||0,w:parseFloat(f.style.width)||f.offsetWidth,r:f.classList.contains('round'),n:f.classList.contains('node'),d:f.classList.contains('dismissed'),p:f.classList.contains('pinned')}}
function save(){if(meta)return;const s={};$$('.frame[data-dynamic="0"]').forEach(f=>s[f.dataset.id]=stateOf(f));try{localStorage.setItem(key(),JSON.stringify(s))}catch{}}
function load(){let s;try{s=JSON.parse(localStorage.getItem(key())||'null')}catch{}$$('.frame[data-dynamic="0"]').forEach(f=>{const v=s?.[f.dataset.id];if(!v)return apply(f);f.style.left=v.l+'px';f.style.top=v.t+'px';f.style.width=f.style.height=v.w+'px';f.classList.toggle('round',v.r);f.classList.toggle('node',v.n);f.classList.toggle('dismissed',v.d);f.classList.toggle('pinned',v.p);scale(f)});bay()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1450)}function bring(f){f.style.zIndex=++z}function shape(f){f.classList.remove('node');f.classList.toggle('round');scale(f);save()}function node(f){if(f.classList.contains('focused'))focus(f);f.classList.toggle('node');if(f.classList.contains('node'))f.classList.add('round');scale(f);save();bay()}function pin(f){f.classList.toggle('pinned');save();toast(f.classList.contains('pinned')?'Pinned':'Unpinned')}
function focus(f){if(!f.classList.contains('focused')){prev={id:f.dataset.id,l:f.style.left,t:f.style.top,w:f.style.width,n:f.classList.contains('node'),r:f.classList.contains('round')};f.classList.remove('node');f.classList.add('focused');document.body.classList.add('focus-mode');const th=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--ticker'))||42,dh=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--dock'))||62,max=Math.min(innerWidth-24,innerHeight-th-dh-24,900),size=[900,720,600,540,480,360].find(x=>x<=max)||Math.floor(max/20)*20;f.style.left=(innerWidth-size)/2+'px';f.style.top=(innerHeight-th-dh-size)/2+'px';f.style.width=f.style.height=size+'px';bring(f)}else{f.classList.remove('focused');document.body.classList.remove('focus-mode');if(prev?.id===f.dataset.id){f.style.left=prev.l;f.style.top=prev.t;f.style.width=f.style.height=prev.w;f.classList.toggle('node',prev.n);f.classList.toggle('round',prev.r)}prev=null;save()}scale(f)}
function dismiss(f){if(f.classList.contains('pinned')){toast('Pinned object');return}if(f.classList.contains('focused'))focus(f);f.classList.add('dismissed');save();bay();toast(`${displayName(f)} dismissed`)}
function displayName(f){return f.querySelector('.name')?.textContent||'Object'}
function duplicate(f){const d={name:displayName(f)+' copy',kind:f.querySelector('.kind')?.textContent||'OBJECT',state:f.querySelector('.state')?.textContent||'READY',html:f.querySelector('.contentFit')?.innerHTML||''};spawn(d,{size:parseFloat(f.style.width)||340,round:f.classList.contains('round')})}
function wire(f){const h=f.querySelector('.head'),n=f.querySelector('.nodeLabel'),r=f.querySelector('.resize');let dr,rs;function start(e,x){if(e.pointerType==='mouse'&&e.button)return;if(f.classList.contains('focused'))return;e.preventDefault();bring(f);x.setPointerCapture(e.pointerId);const b=f.getBoundingClientRect(),th=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--ticker'))||42;dr={id:e.pointerId,sx:e.clientX,sy:e.clientY,l:b.left,t:b.top-th,lx:e.clientX,ly:e.clientY,tm:performance.now(),vx:0,vy:0}}function move(e){if(!dr||e.pointerId!==dr.id)return;const t=performance.now(),dt=Math.max(1,t-dr.tm);dr.vx=(e.clientX-dr.lx)/dt;dr.vy=(e.clientY-dr.ly)/dt;dr.lx=e.clientX;dr.ly=e.clientY;dr.tm=t;f.style.left=Math.max(-f.offsetWidth*.55,Math.min(innerWidth-f.offsetWidth*.45,dr.l+e.clientX-dr.sx))+'px';f.style.top=Math.max(-f.offsetHeight*.55,Math.min($('#viewport').clientHeight-f.offsetHeight*.45,dr.t+e.clientY-dr.sy))+'px';drawLinks()}function end(e,x){if(!dr)return;try{x.releasePointerCapture(e.pointerId)}catch{}if(Math.hypot(dr.vx,dr.vy)>1.55&&!f.classList.contains('pinned')){f.style.transition='.2s';f.style.transform=`translate(${dr.vx*600}px,${dr.vy*600}px)`;f.style.opacity=0;setTimeout(()=>{f.style.transition='';f.style.transform='';f.style.opacity='';dismiss(f)},205)}else save();dr=null}[h,n].forEach(x=>{x.onpointerdown=e=>start(e,x);x.onpointermove=move;x.onpointerup=e=>end(e,x);x.ondblclick=()=>f.classList.contains('node')?node(f):focus(f)});r.onpointerdown=e=>{e.preventDefault();r.setPointerCapture(e.pointerId);rs={id:e.pointerId,sx:e.clientX,sy:e.clientY,w:f.offsetWidth}};r.onpointermove=e=>{if(!rs||e.pointerId!==rs.id)return;const d=Math.max(e.clientX-rs.sx,e.clientY-rs.sy),s=Math.max(160,Math.min(innerWidth*.94,rs.w+d));f.style.width=f.style.height=s+'px';scale(f);drawLinks()};r.onpointerup=()=>{rs=null;save()};f.querySelector('.shape').onclick=e=>{e.stopPropagation();shape(f)};f.querySelector('.node').onclick=e=>{e.stopPropagation();node(f)};f.querySelector('.pin').onclick=e=>{e.stopPropagation();pin(f)};f.querySelector('.duplicate').onclick=e=>{e.stopPropagation();duplicate(f)};f.querySelector('.focus').onclick=e=>{e.stopPropagation();focus(f)};f.querySelector('.dismiss').onclick=e=>{e.stopPropagation();dismiss(f)};f.onpointerdown=()=>bring(f)}
function bay(){const b=$('#objectBay');b.innerHTML='';$$('.frame.dismissed').forEach(f=>{const x=document.createElement('button');x.className='bay';x.dataset.name=displayName(f);x.onclick=()=>{f.classList.remove('dismissed');f.style.left=Math.max(10,(innerWidth-(parseFloat(f.style.width)||250))/2)+'px';f.style.top='60px';bring(f);save();bay()};b.append(x)})}
function openObject(id){const f=$(`.frame[data-id="${CSS.escape(id)}"]`);if(!f)return;f.classList.remove('dismissed');if(f.classList.contains('node'))node(f);if(!f.classList.contains('focused'))focus(f);bay()} C.open=openObject;
function spawn(d,opts={}){const id='dyn-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),f=make(id,d,true);if(opts.size)f.style.width=f.style.height=opts.size+'px';if(opts.round)f.classList.add('round');if(opts.x!=null)f.style.left=opts.x+'px';if(opts.y!=null)f.style.top=opts.y+'px';scale(f);bring(f);drawLinks();return f}
C.spawn=spawn;
function bindObjectActions(f){f.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;e.stopPropagation();if(a==='resume')openObject('resume');else if(a==='workspace')openObject('workspace');else if(a==='changed')toast('State diff will use the private sync layer');else if(a==='quiet'){f.classList.remove('attention');toast('Attention quieted locally')}else if(a==='open-object')showLauncher();else if(a==='chat')spawnChat();else if(a==='terminal')spawnTerminal()})}
function showLauncher(){$('#launcher').classList.add('open');$('#launcher').setAttribute('aria-hidden','false');setTimeout(()=>$('#urlInput').focus(),40)}function hideLauncher(){$('#launcher').classList.remove('open');$('#launcher').setAttribute('aria-hidden','true')}
function viewerShell(label,body,url=''){return `<div class="viewer"><div class="viewerBar"><span class="mediaTitle">${escapeHTML(label)}</span><span class="urlLabel">${escapeHTML(url)}</span>${url?`<button class="externalOpen" data-url="${escapeHTML(url)}">↗</button>`:''}</div><div class="viewerBody">${body}</div></div>`}
function classifyURL(raw){let u;try{u=new URL(raw)}catch{return null}const h=u.hostname.replace(/^www\./,'');let title=h,kind='WEB',src=u.href,type='web';const yt=u.href.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/|embed\/))([^?&/]+)/);const vm=u.href.match(/vimeo\.com\/(?:video\/)?(\d+)/);if(yt){src=`https://www.youtube.com/embed/${yt[1]}?rel=0`;title='YouTube';kind='VIDEO';type='iframe'}else if(vm){src=`https://player.vimeo.com/video/${vm[1]}`;title='Vimeo';kind='VIDEO';type='iframe'}else if(h.includes('docs.google.com')){src=u.href.replace(/\/edit(?:\?.*)?$/,'/preview').replace(/\/view(?:\?.*)?$/,'/preview');title='Google document';kind='DOCUMENT';type='iframe'}else if(/\.(mp4|webm|ogg)(?:$|\?)/i.test(u.pathname)){kind='VIDEO';type='video'}else if(/\.(mp3|wav|m4a|aac)(?:$|\?)/i.test(u.pathname)){kind='AUDIO';type='audio'}else if(/\.pdf(?:$|\?)/i.test(u.pathname)){kind='PDF';type='iframe'}return{url:u.href,src,title,kind,type}}
function openURL(raw,opts={}){const info=classifyURL(raw);if(!info){toast('Not a valid URL');return}let body='';if(info.type==='video')body=`<video controls autoplay src="${escapeHTML(info.src)}"></video>`;else if(info.type==='audio')body=`<audio controls autoplay src="${escapeHTML(info.src)}"></audio>`;else body=`<iframe src="${escapeHTML(info.src)}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" sandbox="allow-same-origin allow-scripts allow-forms allow-popups allow-presentation allow-downloads"></iframe><div class="blockedFallback">If this site refuses to embed, use ↗ to open it directly.</div>`;const d={name:opts.name||info.title,kind:info.kind,state:'LIVE',html:viewerShell(opts.name||info.title,body,info.url)};const f=spawn(d,{size:opts.size||420,round:false});f.dataset.url=info.url;return f}
function openFile(file){const url=URL.createObjectURL(file),name=file.name||'Local file',mime=file.type||'',ext=(name.split('.').pop()||'').toLowerCase();let kind='FILE',body='';if(mime.startsWith('image/')){kind='IMAGE';body=`<img src="${url}" alt="${escapeHTML(name)}">`}else if(mime.startsWith('video/')){kind='VIDEO';body=`<video controls autoplay src="${url}"></video>`}else if(mime.startsWith('audio/')){kind='AUDIO';body=`<audio controls autoplay src="${url}"></audio>`}else if(mime==='application/pdf'||ext==='pdf'){kind='PDF';body=`<iframe src="${url}"></iframe>`}else if(mime.startsWith('text/')||['md','txt','json','csv','log','js','ts','css','html','py','sh'].includes(ext)){kind='TEXT';const d={name,kind,state:'LOCAL',html:viewerShell(name,'<pre class="viewerText">Loading…</pre>')};const f=spawn(d,{size:420});const pre=f.querySelector('.viewerText'),r=new FileReader();r.onload=()=>pre.textContent=String(r.result||'');r.readAsText(file);return f}else{body=`<div class="blockedFallback">${escapeHTML(name)}<br><br>This file type is held as an object but the browser has no native inline renderer.</div>`}return spawn({name,kind,state:'LOCAL',html:viewerShell(name,body)},{size:420})}
function spawnNote(){const f=spawn({name:'Untitled note',kind:'NOTE',state:'LOCAL',html:`<textarea class="noteArea" placeholder="Start typing…"></textarea>`},{size:360});const ta=f.querySelector('textarea');setTimeout(()=>ta?.focus(),60);return f}
function spawnChat(){const html=`<div class="chatSurface"><div class="bridgeState">LIVE CHAT BRIDGE · NOT YET AUTHENTICATED</div><div class="chatLog"><div class="bubble ai">I live here as a native surface. The UI is ready; the private server bridge is the remaining step before this sends to the model.</div></div><div class="chatCompose"><textarea placeholder="Message ChatGPT…"></textarea><button>SEND</button></div></div>`;const f=spawn({name:'ChatGPT',kind:'CHAT',state:'BRIDGE',html},{size:420});const ta=f.querySelector('.chatCompose textarea'),btn=f.querySelector('.chatCompose button'),log=f.querySelector('.chatLog');const send=()=>{const q=ta.value.trim();if(!q)return;log.insertAdjacentHTML('beforeend',`<div class="bubble user">${escapeHTML(q)}</div>`);ta.value='';log.insertAdjacentHTML('beforeend',`<div class="bubble ai">The in-console model bridge is not connected on the public static host yet. I kept your message in this local surface instead of sending it anywhere.</div>`);log.scrollTop=log.scrollHeight;toast('Private chat bridge is next')};btn.onclick=send;ta.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};return f}
function spawnTerminal(){return spawn({name:'Terminal',kind:'SYSTEM',state:'BRIDGE',html:`<div class="terminal"><span class="prompt">observer@console</span>:~$ <span>machine bridge not connected</span><br><br>Future capability: shell · processes · files · telemetry · screen/control</div>`},{size:390})}
function spawnBrowser(){return openURL('https://example.com',{name:'Browser',size:430})}
function handleSpawn(type){hideLauncher();if(type==='file')$('#filePicker').click();else if(type==='url'){showLauncher();$('#urlInput').focus()}else if(type==='note')spawnNote();else if(type==='chat')spawnChat();else if(type==='browser')spawnBrowser();else if(type==='terminal')spawnTerminal()}
function drawLinks(){const svg=$('#links');if(!svg)return;const a=$('.frame[data-id="workspace"]'),p=$('.frame[data-id="projects"]'),r=$('.frame[data-id="resume"]');const pairs=[[a,p,false],[a,r,false],[a,$('.frame[data-id="alerts"]'),true]].filter(x=>x[0]&&x[1]&&!x[0].classList.contains('dismissed')&&!x[1].classList.contains('dismissed'));svg.innerHTML=pairs.map(([x,y,hot])=>{const xb=x.getBoundingClientRect(),yb=y.getBoundingClientRect(),v=$('#viewport').getBoundingClientRect();return `<line class="linkLine ${hot?'hot':''}" x1="${xb.left-v.left+xb.width/2}" y1="${xb.top-v.top+xb.height/2}" x2="${yb.left-v.left+yb.width/2}" y2="${yb.top-v.top+yb.height/2}"/>`}).join('')}
$('#focusDim').onclick=()=>{const f=$('.frame.focused');if(f)focus(f)};$('#attentionPull').onclick=()=>openObject('alerts');$('#restoreAll').onclick=()=>{$$('.frame.dismissed').forEach(f=>f.classList.remove('dismissed'));save();bay();drawLinks();toast('Objects restored')};$('#displayMode').onclick=()=>location.href='meta.html';$('#assistantButton').onclick=spawnChat;$('#addObject').onclick=showLauncher;$('#filePicker').onchange=e=>{[...e.target.files].forEach(openFile);e.target.value=''};$('#launcher').onclick=e=>{if(e.target.id==='launcher'||e.target.closest('[data-close]'))hideLauncher();const t=e.target.closest('[data-spawn]')?.dataset.spawn;if(t)handleSpawn(t)};$('#openUrl').onclick=()=>{const v=$('#urlInput').value.trim();if(v){hideLauncher();openURL(v);$('#urlInput').value=''}};$('#urlInput').onkeydown=e=>{if(e.key==='Enter')$('#openUrl').click()};
document.addEventListener('click',e=>{const ext=e.target.closest('.externalOpen');if(ext){window.open(ext.dataset.url,'_blank','noopener');e.stopPropagation()}});
$('#command').onkeydown=e=>{if(e.key!=='Enter')return;const raw=e.target.value.trim(),q=raw.toLowerCase();if(/^https?:\/\//i.test(raw))openURL(raw);else if(q.startsWith('open ')&&/^https?:\/\//i.test(raw.slice(5).trim()))openURL(raw.slice(5).trim());else if(q.includes('chat')||q.includes('ask'))spawnChat();else if(q.includes('note'))spawnNote();else if(q.includes('terminal')||q.includes('shell'))spawnTerminal();else if(q.includes('file')||q.includes('document'))$('#filePicker').click();else{const m=[['resume','resume'],['where','resume'],['mail','inbox'],['inbox','inbox'],['calendar','calendar'],['meeting','calendar'],['system','systems'],['machine','systems'],['project','projects'],['alert','alerts'],['reality','workspace'],['now','overview']].find(([k])=>q.includes(k));m?openObject(m[1]):showLauncher()}e.target.value=''};
function ticks(){return[['WEATHER',window.__weather||'LAS VEGAS · LIVE','overview',0],['MAIL','CONNECTED','inbox',0],['CALENDAR','CONNECTED','calendar',0],['ATTENTION','1 SIGNAL','alerts',1],['REALITY-CODE','RCX-0005 OPEN','workspace',0],['LIFE-CODE','A3 ACTIVE','projects',0],['OBJECTS',String($$('.frame:not(.dismissed)').length),'overview',0]]}function ticker(){const a=[...ticks(),...ticks()];$('#tickerTrack').innerHTML=a.map(([k,v,id,h])=>`<span class="tick ${h?'hot':''}" data-id="${id}"><strong>${k}</strong>${v}</span>`).join('');$$('.tick').forEach(t=>t.onclick=()=>meta?C.metaSelect?.(t.dataset.id):openObject(t.dataset.id))}
ticker();fetch('https://api.open-meteo.com/v1/forecast?latitude=36.1699&longitude=-115.1398&current=temperature_2m,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph').then(r=>r.json()).then(j=>{window.__weather=`LAS VEGAS · ${Math.round(j.current.temperature_2m)}°F · ${Math.round(j.current.wind_speed_10m)} MPH`;const w=$('#weatherInline');if(w)w.textContent=window.__weather;ticker()}).catch(()=>{});
const vp=$('#viewport');['dragenter','dragover'].forEach(ev=>vp.addEventListener(ev,e=>{e.preventDefault();dragDepth++;document.body.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>vp.addEventListener(ev,e=>{e.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(ev==='drop'||dragDepth===0)document.body.classList.remove('dragging')}));vp.addEventListener('drop',e=>{const files=[...e.dataTransfer.files];if(files.length){files.forEach(openFile);return}const uri=e.dataTransfer.getData('text/uri-list')||e.dataTransfer.getData('text/plain');if(/^https?:\/\//i.test(uri.trim()))openURL(uri.trim());else if(uri.trim())spawn({name:'Dropped text',kind:'TEXT',state:'LOCAL',html:viewerShell('Dropped text',`<pre class="viewerText">${escapeHTML(uri)}</pre>`)},{size:340})});
document.addEventListener('paste',e=>{if(e.target.matches('input,textarea,[contenteditable]'))return;const t=e.clipboardData?.getData('text/plain')?.trim();if(/^https?:\/\//i.test(t||''))openURL(t)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#launcher').classList.contains('open'))hideLauncher();else{const f=$('.frame.focused');if(f)focus(f)}}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#command').focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();showLauncher()}});
if(!meta)load();setTimeout(()=>{$$('.frame').forEach(scale);drawLinks()},60);addEventListener('resize',()=>{if(meta)return;clearTimeout(window._rr);window._rr=setTimeout(()=>{load();drawLinks()},160)});
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
