window.CONSOLE={
DATA:{
workspace:{name:'WORKSPACE',state:'ACTIVE',hot:false,title:'Reality-Code',sub:'v5.8 · current context',html:`<div class="kicker">CURRENT WORKSPACE</div><div class="hero">Reality-Code</div><div class="sub">v5.8 · active context</div><div class="divider"></div><div class="stats"><div class="stat"><b>OPEN FRONT</b><span>RCX-0005</span></div><div class="stat"><b>STATE</b><span>OPEN</span></div><div class="stat"><b>CONTROL</b><span>0006B PASS</span></div><div class="stat"><b>NEXT</b><span>Resume runtime</span></div></div><div class="actions"><button class="action" data-action="resume">RESUME</button><button class="action" data-action="changed">WHAT CHANGED?</button></div>`},
alerts:{name:'ALERTS',state:'1 ITEM',hot:true,title:'Alerts',sub:'one item needs you',html:`<div class="kicker">NEEDS ATTENTION</div><div class="hero">1 item</div><div class="sub">Interface iteration</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Review current build</b><small>Active because you are working here now</small></div><em>NOW</em></div></div><div class="actions"><button class="action" data-action="workspace">OPEN</button><button class="action" data-action="quiet">QUIET</button></div>`},
resume:{name:'RESUME',state:'RECENT',hot:false,title:'Resume',sub:'pick up where you stopped',html:`<div class="kicker">WHERE YOU WERE</div><div class="hero">Resume</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Interface</b><small>hosted spatial console · v0.8</small></div><em>NOW</em></div><div class="row"><span class="bar"></span><div><b>Reality-Code</b><small>RCX-0005 remains open</small></div><em>OPEN</em></div><div class="row"><span class="bar"></span><div><b>LIFE-CODE</b><small>A3 remains active</small></div><em>RUN</em></div></div><div class="actions"><button class="action" data-action="resume">RECONSTRUCT</button></div>`},
overview:{name:'OVERVIEW',state:'LIVE',hot:false,title:'Overview',sub:'what matters now',html:`<div class="kicker">AT A GLANCE</div><div class="hero">Now</div><div class="divider"></div><div class="stats"><div class="stat"><b>INBOX</b><span>200,606 unread</span></div><div class="stat"><b>NEXT</b><span>Sep 23 · 15:45</span></div><div class="stat"><b>SYSTEMS</b><span>2 online</span></div><div class="stat"><b>ALERTS</b><span>1 active</span></div></div>`},
systems:{name:'SYSTEMS',state:'2 ONLINE',hot:false,title:'Systems',sub:'machines and processes',html:`<div class="kicker">MACHINES</div><div class="hero">Systems</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Primary workstation</b><small>online · local</small></div><em>ON</em></div><div class="row"><span class="bar"></span><div><b>LIFE-CODE / WSL</b><small>A3 process active</small></div><em>RUN</em></div><div class="row"><span class="bar"></span><div><b>Mina node</b><small>not connected yet</small></div><em>OFF</em></div></div>`},
projects:{name:'PROJECTS',state:'4 ACTIVE',hot:false,title:'Projects',sub:'active operational contexts',html:`<div class="kicker">PROJECTS</div><div class="hero">Active</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Reality-Code</b><small>experiment track</small></div><em>ACTIVE</em></div><div class="row"><span class="bar"></span><div><b>LIFE-CODE</b><small>codebook + experiment</small></div><em>RUN</em></div><div class="row"><span class="bar"></span><div><b>Abnormal Observations</b><small>content system</small></div><em>LIVE</em></div><div class="row"><span class="bar"></span><div><b>Murphy's Law</b><small>business operations</small></div><em>OPS</em></div></div>`},
inbox:{name:'INBOX',state:'CONNECTED',hot:false,title:'Inbox',sub:'priority over volume',html:`<div class="kicker">INBOX</div><div class="hero">200,606</div><div class="sub">unread messages</div><div class="divider"></div><div class="muted" style="font-size:11px;line-height:1.5">The useful layer is priority, not raw volume. Connected triage comes next.</div><div class="actions"><button class="action" data-action="inbox">TRIAGE</button></div>`},
calendar:{name:'CALENDAR',state:'SEP 23',hot:false,title:'Calendar',sub:'next known event',html:`<div class="kicker">CALENDAR</div><div class="hero">Sep 23</div><div class="sub">15:45 · Payday</div><div class="divider"></div><div class="stat"><b>NEXT KNOWN ITEM</b><span>Payday</span></div><div class="actions"><button class="action" data-action="calendar">OPEN</button></div>`},
assistant:{name:'ASSISTANT',state:'READY',hot:false,title:'Assistant',sub:'AI command layer',html:`<div class="kicker">COMMAND</div><div class="hero">Assistant</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Where was I?</b><small>reconstruct active context</small></div><em>ASK</em></div><div class="row"><span class="bar"></span><div><b>What changed?</b><small>state diff since last view</small></div><em>ASK</em></div><div class="row"><span class="bar"></span><div><b>Show what needs me</b><small>attention-ranked only</small></div><em>ASK</em></div></div><div class="actions"><button class="action" data-action="command">TYPE</button></div>`}
},
ORDER:['workspace','alerts','resume','overview','systems','projects','inbox','calendar','assistant'],
META:['workspace','alerts','resume','overview','systems','projects','assistant','inbox','calendar'],
metaRows:{workspace:['v5.8 · current context','RCX-0005 · OPEN','Next · resume runtime'],alerts:['1 item needs attention','Interface review','No critical alert'],resume:['Console · hosted v0.8','Reality-Code · RCX-0005','LIFE-CODE · A3'],overview:['Inbox · 200,606 unread','Calendar · Sep 23 15:45','Weather · live'],systems:['Primary workstation · online','LIFE-CODE / WSL · active','Mina node · unlinked'],projects:['Reality-Code · active','LIFE-CODE · running','Abnormal Observations · live',"Murphy's Law · ops"],assistant:['Where was I?','What changed?','Show what needs me'],inbox:['200,606 unread','Priority triage next','Raw count is not the UI'],calendar:['Sep 23 · 15:45','Payday','Open for full schedule']}
};
