window.CONSOLE={
VERSION:'0.9',
DATA:{
workspace:{name:'Reality-Code',kind:'PROJECT',state:'RCX-0005 OPEN',hot:false,html:`<div class="kicker">CURRENT PROJECT</div><div class="hero">Reality-Code</div><div class="sub">v5.8 · current context</div><div class="divider"></div><div class="stats"><div class="stat"><b>OPEN FRONT</b><span>RCX-0005</span></div><div class="stat"><b>CONTROL</b><span>0006B PASS</span></div><div class="stat"><b>STATE</b><span>OPEN</span></div><div class="stat"><b>NEXT</b><span>Resume runtime</span></div></div><div class="actions"><button class="action" data-action="resume">RESUME</button><button class="action" data-action="changed">WHAT CHANGED?</button></div>`},
alerts:{name:'Attention',kind:'ALERT',state:'1 ITEM',hot:true,html:`<div class="kicker">NEEDS YOU</div><div class="hero">1 signal</div><div class="sub">Interface build is active</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Current build</b><small>High relevance because you are working here now</small></div><em>NOW</em></div></div><div class="actions"><button class="action" data-action="workspace">OPEN</button><button class="action" data-action="quiet">QUIET</button></div>`},
resume:{name:'Resume',kind:'CONTINUITY',state:'RECENT',hot:false,html:`<div class="kicker">WHERE YOU WERE</div><div class="hero">Resume</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Console</b><small>object-first capability build · v0.9</small></div><em>NOW</em></div><div class="row"><span class="bar"></span><div><b>Reality-Code</b><small>RCX-0005 remains open</small></div><em>OPEN</em></div><div class="row"><span class="bar"></span><div><b>LIFE-CODE</b><small>A3 remains active</small></div><em>RUN</em></div></div>`},
overview:{name:'Now',kind:'STATUS',state:'LIVE',hot:false,html:`<div class="kicker">AT A GLANCE</div><div class="hero">Now</div><div class="divider"></div><div class="stats"><div class="stat"><b>MAIL</b><span>connected</span></div><div class="stat"><b>CALENDAR</b><span>connected</span></div><div class="stat"><b>SYSTEMS</b><span>bridge pending</span></div><div class="stat"><b>WEATHER</b><span id="weatherInline">live</span></div></div><div class="actions"><button class="action" data-action="open-object">OPEN ANYTHING</button></div>`},
systems:{name:'Systems',kind:'SYSTEMS',state:'BRIDGE READY',hot:false,html:`<div class="kicker">MACHINES</div><div class="hero">Systems</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Primary workstation</b><small>desktop companion target</small></div><em>LOCAL</em></div><div class="row"><span class="bar"></span><div><b>LIFE-CODE / WSL</b><small>process telemetry target</small></div><em>RUN</em></div><div class="row"><span class="bar"></span><div><b>Mina node</b><small>remote node target</small></div><em>LINK</em></div></div><div class="actions"><button class="action" data-action="terminal">TERMINAL</button></div>`},
projects:{name:'Projects',kind:'PROJECTS',state:'ACTIVE',hot:false,html:`<div class="kicker">ACTIVE CONTEXTS</div><div class="hero">Projects</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Reality-Code</b><small>experiment track</small></div><em>OPEN</em></div><div class="row"><span class="bar"></span><div><b>LIFE-CODE</b><small>codebook + experiment</small></div><em>RUN</em></div><div class="row"><span class="bar"></span><div><b>Abnormal Observations</b><small>content + identity</small></div><em>LIVE</em></div><div class="row"><span class="bar"></span><div><b>Murphy's Law</b><small>business operations</small></div><em>OPS</em></div></div>`},
inbox:{name:'Inbox',kind:'MAIL',state:'CONNECTED',hot:false,html:`<div class="kicker">MAIL</div><div class="hero">Inbox</div><div class="sub">priority over volume</div><div class="divider"></div><div class="muted copy">The hosted shell will not expose private mail. The private connector layer will stream priority messages into this same object once the backend gate is live.</div>`},
calendar:{name:'Calendar',kind:'CALENDAR',state:'CONNECTED',hot:false,html:`<div class="kicker">SCHEDULE</div><div class="hero">Calendar</div><div class="divider"></div><div class="list"><div class="row"><span class="bar"></span><div><b>Next known item</b><small>Sep 23 · 15:45</small></div><em>PAYDAY</em></div></div>`},
assistant:{name:'ChatGPT',kind:'ASSISTANT',state:'SURFACE READY',hot:false,html:`<div class="kicker">ASSISTANT</div><div class="hero">ChatGPT</div><div class="divider"></div><div class="chatPreview"><div class="bubble ai">Ask from anywhere in the environment.</div><div class="bubble user">Operate on the object I am looking at.</div></div><div class="actions"><button class="action" data-action="chat">OPEN CHAT</button></div>`}
},
ORDER:['workspace','alerts','resume','overview','systems','projects','inbox','calendar','assistant'],
META:['workspace','alerts','resume','overview','systems','projects','assistant','inbox','calendar'],
metaRows:{workspace:['v5.8 · current context','RCX-0005 · OPEN','Next · resume runtime'],alerts:['1 signal needs attention','Current build active','No critical alert'],resume:['Console · capability build','Reality-Code · RCX-0005','LIFE-CODE · A3'],overview:['Mail · connected','Calendar · connected','Weather · live'],systems:['Primary workstation · target','LIFE-CODE / WSL · target','Mina node · target'],projects:['Reality-Code · open','LIFE-CODE · running','Abnormal Observations · live',"Murphy's Law · ops"],assistant:['Context-aware assistant','Object actions','Backend bridge next'],inbox:['Private connector layer','Priority triage','No public data'],calendar:['Private connector layer','Next known · Sep 23','No public data']}
};
