(()=>{'use strict';
const V='0.11.0',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],C=window.CONSOLE||{},K='lc-world-v011',OLD='lc-world-v010',DK='lc-device-v1';
const S={secret:'',world:'',device:'',snap:null,live:false,rt:false,busy:false,client:null,ch:null,pres:{},apply:false,timer:null,sig:new Map(),err:''};
const cfg=()=>window.LC_CLOUD_CONFIG||{},profile=()=>document.body.classList.contains('meta')?'meta':innerWidth<=720?'mobile':'desktop';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const toast=t=>{let e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)};
function hex(n=32){let a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(b=>b.toString(16).padStart(2,'0')).join('')}
function uuid(){return crypto.randomUUID?crypto.randomUUID():stable(hex())}
function stable(s){let h=[2166136261,2654435761,2246822507,3266489909];for(let c of s)for(let i=0;i<4;i++){h[i]^=c.charCodeAt(0)+i*31;h[i]=Math.imul(h[i],16777619)>>>0}let x=h.map(v=>v.toString(16).padStart(8,'0')).join('').slice(0,32).split('');x[12]='5';x[16]=((parseInt(x[16],16)&3)|8).toString(16);x=x.join('');return`${x.slice(0,8)}-${x.slice(8,12)}-${x.slice(12,16)}-${x.slice(16,20)}-${x.slice(20)}`}
async function hash(s){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function load(){try{let a=JSON.parse(localStorage.getItem(K)||'{}'),b=JSON.parse(localStorage.getItem(OLD)||'{}');S.secret=a.secret||b.secret||'';S.world=a.world||a.worldId||b.worldId||''}catch{}try{S.device=localStorage.getItem(DK)||uuid();localStorage.setItem(DK,S.device)}catch{S.device=uuid()}}
function saveId(){try{localStorage.setItem(K,JSON.stringify({secret:S.secret,world:S.world,version:V}))}catch{}}
async function rpc(n,a={}){let c=cfg();if(!c.url||!c.anonKey)throw Error('Supabase not bound');let r=await fetch(c.url.replace(/\/$/,'')+'/rest/v1/rpc/'+n,{method:'POST',headers:{apikey:c.anonKey,Authorization:'Bearer '+c.anonKey,'Content-Type':'application/json'},body:JSON.stringify(a)}),t=await r.text();if(!r.ok){try{throw Error(JSON.parse(t).message||t)}catch(e){if(e instanceof SyntaxError)throw Error(t)}}try{return JSON.parse(t)}catch{return t}}
function frames(){return $$('.frame')}
function cid(f){if(f.dataset.cloudId)return f.dataset.cloudId;return f.dataset.cloudId=f.dataset.dynamic==='0'?stable('builtin:'+f.dataset.id):uuid()}
function view(f){return{l:Math.round(parseFloat(f.style.left)||0),t:Math.round(parseFloat(f.style.top)||0),w:Math.round(parseFloat(f.style.width)||f.offsetWidth||320),round:f.classList.contains('round'),node:f.classList.contains('node'),dismissed:f.classList.contains('dismissed'),pinned:f.classList.contains('pinned')}}
function obj(f){let h=$('.contentFit',f)?.innerHTML||'',note=$('.noteArea',f)?.value??null,b=f.dataset.dynamic==='0',trans=/blob:/i.test(h);return{id:cid(f),kind:$('.kind',f)?.textContent||'OBJECT',title:$('.name',f)?.textContent||f.dataset.id||'Object',state:$('.state',f)?.textContent||'READY',source:b?{type:'builtin',builtin_id:f.dataset.id}:{type:f.dataset.url?'url':'console',url:f.dataset.url||null},payload:b?{builtin_id:f.dataset.id}:{html:trans?'':h,note,transient:trans}}}
function apply(f,v){if(!v)return;S.apply=true;if(v.l!=null)f.style.left=v.l+'px';if(v.t!=null)f.style.top=v.t+'px';if(v.w){f.style.width=f.style.height=v.w+'px'}f.classList.toggle('round',!!v.round);f.classList.toggle('node',!!v.node);f.classList.toggle('dismissed',!!v.dismissed);f.classList.toggle('pinned',!!v.pinned);requestAnimationFrame(()=>{S.apply=false;dispatchEvent(new Event('resize'))})}
function cloudView(id){return(S.snap?.views||[]).find(v=>v.object_id===id&&v.viewport===profile())?.view}
function cloudObj(id){return(S.snap?.objects||[]).find(o=>o.id===id)}
function local(id){return frames().find(f=>f.dataset.cloudId===id)}
function materialize(o){if(!C.spawn)return;S.apply=true;let p=o.payload||{},f=C.spawn({name:o.title,kind:o.kind,state:o.state,html:p.html|| (p.transient?'<div class="blockedFallback">Local binary metadata synchronized; binary remains on the source device.</div>':'')},{size:cloudView(o.id)?.w||360});f.dataset.cloudId=o.id;f.dataset.cloud='live';if(o.source?.url)f.dataset.url=o.source.url;let n=$('.noteArea',f);if(n&&p.note!=null)n.value=p.note;apply(f,cloudView(o.id));setTimeout(()=>S.apply=false,0)}
function applySnap(s){S.snap=s;S.world=s?.world_id||S.world;saveId();let ids=new Set((s?.objects||[]).map(o=>o.id));frames().filter(f=>f.dataset.dynamic==='0').forEach(f=>{let id=cid(f);f.dataset.cloud='live';apply(f,cloudView(id))});(s?.objects||[]).filter(o=>o.source?.type!=='builtin').forEach(o=>{let f=local(o.id);if(!f)materialize(o);else{let n=$('.noteArea',f);if(n&&o.payload?.note!=null&&document.activeElement!==n)n.value=o.payload.note;apply(f,cloudView(o.id));f.dataset.cloud='live'}});$('#worldIdentity')&&($('#worldIdentity').textContent=S.world?S.world.slice(0,8)+' · '+profile().toUpperCase():'UNBOUND')}
async function saveFrame(f,force=false){if(!S.live||S.apply||!f)return false;let o=obj(f),v=view(f),sig=JSON.stringify([o,v]);if(!force&&S.sig.get(o.id)===sig)return false;f.dataset.cloud='syncing';await rpc('lc_save_object',{p_secret:S.secret,p_object:o});await rpc('lc_save_view',{p_secret:S.secret,p_object_id:o.id,p_viewport:profile(),p_view:v});S.sig.set(o.id,sig);f.dataset.cloud='live';return true}
async function saveAll(force=false){if(S.busy)return;S.busy=true;status();try{let n=0;for(let f of frames())if(await saveFrame(f,force))n++;if(n)await pulse('save');await sync(false);toast(n?'WORLD saved':'WORLD current')}catch(e){S.err=e.message;toast('WORLD save failed')}S.busy=false;status()}
async function sync(manual=false){if(!S.secret||S.busy)return;S.busy=true;status();try{let s=await rpc('lc_world_snapshot',{p_secret:S.secret});applySnap(s);S.live=true;S.err='';let missing=frames().filter(f=>f.dataset.dynamic==='0'&&!cloudObj(cid(f)));for(let f of missing)await saveFrame(f,true);if(missing.length)applySnap(await rpc('lc_world_snapshot',{p_secret:S.secret}));if(manual)toast('WORLD synchronized')}catch(e){S.err=e.message;S.live=false;if(manual)toast('Sync failed')}S.busy=false;status();render()}
function schedule(f){if(S.apply||!S.live)return;clearTimeout(f._sync);f._sync=setTimeout(async()=>{try{if(await saveFrame(f))await pulse('object')}catch(e){S.err=e.message;status()}},450)}
function count(){return Object.keys(S.pres||{}).length||(S.rt?1:0)}
function status(){let b=$('#worldStatus');if(!b)return;b.dataset.state=S.busy?'syncing':S.err?'error':S.live?'live':'idle';b.textContent=S.busy?'SYNC':S.err?'WORLD!':'WORLD·'+Math.max(1,count())}
function label(){let u=navigator.userAgent||'',d=/Quest|Oculus/i.test(u)?'META':/Android/i.test(u)?'ANDROID':/iPhone|iPad/i.test(u)?'IOS':/Windows/i.test(u)?'WINDOWS':/Macintosh/i.test(u)?'MAC':'BROWSER';return d+' '+profile().toUpperCase()}
async function realtime(){if(!window.supabase?.createClient)return;try{if(S.client&&S.ch)await S.client.removeChannel(S.ch);S.client=window.supabase.createClient(cfg().url,cfg().publishableKey||cfg().anonKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});let topic='lc-'+(await hash(S.secret)).slice(0,24),ch=S.client.channel(topic,{config:{broadcast:{ack:true},presence:{key:S.device}}});S.ch=ch;ch.on('broadcast',{event:'invalidate'},p=>{if(p.payload?.device!==S.device)sync(false)}).on('presence',{event:'sync'},()=>{S.pres=ch.presenceState()||{};S.rt=true;status();render()}).subscribe(async st=>{S.rt=st==='SUBSCRIBED';if(S.rt)await ch.track({device:S.device,label:label(),view:profile(),online_at:new Date().toISOString(),version:V});status();render()})}catch(e){S.rt=false}}
async function pulse(reason){try{if(S.ch&&S.rt)await S.ch.send({type:'broadcast',event:'invalidate',payload:{device:S.device,reason,at:Date.now()}})}catch{}}
function pairFromUrl(){let u=new URL(location.href),q=u.searchParams.get('pair');return(q||'').toUpperCase()}
function clearPair(){let u=new URL(location.href);u.searchParams.delete('pair');history.replaceState(null,'',u.pathname+(u.searchParams.toString()?'?'+u.searchParams:''))}
async function claim(code){let sec=await rpc('lc_claim_pair',{p_code:String(code||'').replace(/\W/g,'').toUpperCase()});if(!sec||String(sec).length<48)throw Error('Bad pair code');S.secret=String(sec);S.world='';saveId();S.world=await rpc('lc_bootstrap_world',{p_secret:S.secret,p_name:'Primary World'});saveId();await sync(false);await realtime();toast('Device joined WORLD');select('devices')}
async function bootWorld(){let pc=pairFromUrl();if(pc){try{await claim(pc);clearPair();return}catch{clearPair();toast('Pair link expired')}}if(!S.secret){S.secret=hex();saveId()}S.world=await rpc('lc_bootstrap_world',{p_secret:S.secret,p_name:'Primary World'});S.live=true;saveId();await sync(false);await realtime();clearInterval(S.timer);S.timer=setInterval(()=>document.visibilityState==='visible'&&sync(false),5000)}
function install(){if($('#worldStatus'))return;let b=document.createElement('button');b.id='worldStatus';b.className='topControl worldStatus';b.textContent='WORLD';b.onclick=()=>open('sync');$('#ticker')?.append(b);let d=document.createElement('button');d.id='worldButton';d.className='dockBtn';d.textContent='WORLD';d.onclick=()=>open('sync');$('#dock')?.insertBefore(d,$('#assistantButton'));let o=document.createElement('div');o.id='worldOverlay';o.className='overlay worldOverlay';o.innerHTML='<div class="worldShell"><div class="worldHead"><div><b>WORLD</b><span id="worldIdentity">CONNECTING</span></div><button id="worldClose">×</button></div><div class="worldTabs"><button data-tab="sync" class="active">SYNC</button><button data-tab="devices">DEVICES</button><button data-tab="pair">PAIR</button></div><div id="worldBody" class="worldBody"></div></div>';document.body.append(o);$('#worldClose').onclick=close;$$('[data-tab]').forEach(x=>x.onclick=()=>select(x.dataset.tab));status()}
function open(t='sync'){$('#worldOverlay').classList.add('open');select(t)}function close(){$('#worldOverlay').classList.remove('open')}function select(t){$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));$('#worldOverlay').dataset.tab=t;render()}
function render(){let r=$('#worldBody');if(!r||!$('#worldOverlay')?.classList.contains('open'))return;let t=$('#worldOverlay').dataset.tab||'sync';if(t==='sync'){r.innerHTML=`<div class="syncHero"><div class="syncOrb ${S.live?'live':''}"></div><div><b>${S.live?'WORLD ONLINE':'WORLD OFFLINE'}</b><span>${esc(S.world||'unbound')}</span></div></div><div class="syncStats"><div><b>VIEW</b><span>${profile().toUpperCase()}</span></div><div><b>DEVICES</b><span>${count()}</span></div><div><b>TRANSPORT</b><span>${S.rt?'REALTIME':'POLL'}</span></div><div><b>VERSION</b><span>${V}</span></div></div><div class="syncActions"><button id="snow">SYNC NOW</button><button id="sall">SAVE VIEW</button><button id="spair">PAIR DEVICE</button></div>${S.err?'<div class="syncDetail"><p>'+esc(S.err)+'</p></div>':''}`;$('#snow').onclick=()=>sync(true);$('#sall').onclick=()=>saveAll(true);$('#spair').onclick=()=>select('pair')}else if(t==='devices'){let a=[];Object.entries(S.pres||{}).forEach(([k,v])=>(v||[]).forEach(x=>a.push(x)));if(!a.length)a=[{device:S.device,label:label(),view:profile(),online_at:new Date().toISOString()}];r.innerHTML='<div class="sourceGrid">'+a.map(x=>`<div class="sourceCard live"><b>${esc(x.label||'DEVICE')}</b><span>${esc((x.view||'view').toUpperCase())}${x.device===S.device?' · THIS DEVICE':''}</span><small>${esc(String(x.device||'').slice(0,12))}</small></div>`).join('')+'</div><div class="syncActions"><button id="ptest">SEND TEST PULSE</button></div>';$('#ptest').onclick=()=>pulse('test')}else{r.innerHTML='<div class="pairGrid"><section><b>PAIR ANOTHER DEVICE</b><p>Create a five-minute link, then open it on the other device.</p><button id="issue">CREATE PAIR LINK</button><div id="pairOut"></div></section><section><b>JOIN THIS WORLD</b><input id="code" maxlength="12" placeholder="PAIR CODE"><button id="join">JOIN WORLD</button></section></div>';$('#issue').onclick=async()=>{try{let c=await rpc('lc_issue_pair',{p_secret:S.secret}),u=new URL(location.href);u.search='';u.searchParams.set('pair',c);$('#pairOut').innerHTML='<div class="pairCode">'+esc(c)+'</div><p style="word-break:break-all">'+esc(u)+'</p><button id="copy">COPY LINK</button>';$('#copy').onclick=()=>navigator.clipboard?.writeText(String(u)).then(()=>toast('Pair link copied'))}catch(e){toast('Pair failed')}};$('#join').onclick=()=>claim($('#code').value).catch(()=>toast('Invalid pair code'))}}
function hooks(){let w=$('#workspace');new MutationObserver(m=>{if(S.apply)return;m.forEach(r=>r.addedNodes.forEach(n=>n.nodeType===1&&n.matches?.('.frame')&&schedule(n))) }).observe(w,{childList:true});document.addEventListener('pointerup',e=>{let f=e.target.closest?.('.frame');if(f)schedule(f)},true);document.addEventListener('click',e=>{let f=e.target.closest?.('.frame');if(f)schedule(f)},true);document.addEventListener('input',e=>{let f=e.target.closest?.('.frame');if(f)schedule(f)},true);document.addEventListener('visibilitychange',()=>document.visibilityState==='visible'&&sync(false))}
async function boot(){load();install();hooks();try{await bootWorld()}catch(e){S.err=e.message;S.live=false;status();toast('WORLD offline')}render()}
C.world={version:V,state:S,sync:()=>sync(true),save:()=>saveAll(true),open,pair:()=>select('pair')};
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();
